In [2]:
import torch
from numpy.linalg import norm
import numpy as np
%matplotlib inline

In [3]:
torch.cuda.is_available()

True

In [4]:
t = torch.tensor([1., 1., 1.], requires_grad=False, dtype=torch.float).cuda()

In [5]:
a = torch.tensor([5., 5., 5.], requires_grad=False).cuda()

In [6]:
t + a

tensor([6., 6., 6.], device='cuda:0')

In [7]:
!nvidia-smi

Fri May 20 00:23:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 42%   43C    P0    28W /  90W |    914MiB /  2048MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [8]:
torch.vstack([t, a])

tensor([[1., 1., 1.],
        [5., 5., 5.]], device='cuda:0')

In [9]:
norm(t.cpu().numpy())

1.7320508

In [10]:
t[1] += 1

In [11]:
t

tensor([1., 2., 1.], device='cuda:0')

In [12]:
torch.zeros(3)

tensor([0., 0., 0.])

In [13]:
np.array([1, 2, 3])[1].item()

2

In [14]:
print(t)
t[1] += t[2] - 5 * 3.5

tensor([1., 2., 1.], device='cuda:0')


In [15]:
t

tensor([  1.0000, -14.5000,   1.0000], device='cuda:0')

In [16]:
t += np.random.uniform(-1 / 20, 1 / 20)

In [17]:
t

tensor([  1.0029, -14.4971,   1.0029], device='cuda:0')

In [18]:
t[0] -= 1234

In [19]:
t[1] = 0.123123123123

In [20]:
t.cpu().numpy()

array([-1.23299707e+03,  1.23123124e-01,  1.00287974e+00], dtype=float32)

In [21]:
!nvidia-smi

Fri May 20 00:23:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 42%   43C    P0    28W /  90W |    913MiB /  2048MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [22]:
from math import pow, sqrt
import numpy as np

In [23]:
kT = 26.5
N = 150

Пиковое значение распределния Максвелла:

In [24]:
sqrt(1. / (2 * np.pi * kT)) * (8 * np.pi * kT / np.e)

18.98796316581417

In [25]:
import pandas as pd

In [26]:
dic = {'a': [1], 'b': [2], 'c': [3]}

df = pd.DataFrame(
    dic
)

df = pd.concat([df, pd.DataFrame({'a': [1], 'b': [2], 'c': [3]})])

df

a  b  c
0  1  2  3
0  1  2  3

In [30]:
1 in list(df.a)

[1, 1]