In [8]:
import torch
from numpy.linalg import norm
import numpy as np
%matplotlib inline

In [3]:
torch.cuda.is_available()

True

In [95]:
t = torch.tensor([1., 1., 1.], requires_grad=False, dtype=torch.float).cuda()

In [94]:
a = torch.tensor([5., 5., 5.], requires_grad=False).cuda()

In [58]:
t + a

tensor([6, 6, 6], device='cuda:0')

In [53]:
!nvidia-smi

Sat Mar 26 20:14:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| 41%   47C    P0    29W /  90W |   1062MiB /  2048MiB |      8%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [70]:
torch.vstack([t, a])

tensor([[1, 1, 1],
        [5, 5, 5]], device='cuda:0')

In [78]:
norm(t.cpu().numpy())

1.7320508075688772

In [83]:
t[1] += 1

In [84]:
t

tensor([1, 2, 1], device='cuda:0')

In [85]:
torch.zeros(3)

tensor([0., 0., 0.])

In [86]:
np.array([1, 2, 3])[1].item()

2

In [103]:
print(t)
t[1] += t[2] - 5 * 3.5

tensor([-1.2330e+03, -1.5497e+01,  1.0030e+00], device='cuda:0')


In [97]:
t

tensor([  1.0000, -15.5000,   1.0000], device='cuda:0')

In [98]:
t += np.random.uniform(-1 / 20, 1 / 20)

In [99]:
t

tensor([  1.0030, -15.4970,   1.0030], device='cuda:0')

In [101]:
t[0] -= 1234

In [105]:
t[1] = 0.123123123123

In [108]:
t.cpu().numpy()

array([-1.23299707e+03,  1.23123124e-01,  1.00297105e+00], dtype=float32)

In [119]:
!nvidia-smi

Sat Mar 26 21:28:59 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| 42%   43C    P0    28W /  90W |   1732MiB /  2048MiB |     22%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
from math import pow, sqrt
import numpy as np

In [1]:
kT = 26.5
N = 150

Пиковое значение распределния Максвелла:

In [6]:
sqrt(1. / (2 * np.pi * kT)) * (8 * np.pi * kT / np.e)

18.98796316581417