In [1]:
import torch
from numpy.linalg import norm
import numpy as np
%matplotlib inline

In [12]:
torch.cuda.is_available()

False

In [8]:
if torch.cuda.is_available():
    device=torch.device('cuda')
else:
    device=torch.device('cpu')

In [9]:
t = torch.tensor([1., 1., 1.], requires_grad=False, dtype=torch.float, device=device)

In [11]:
a = torch.tensor([5., 5., 5.], requires_grad=False, device=device)

In [ ]:
t + a

tensor([6., 6., 6.], device='cuda:0')

In [ ]:
!nvidia-smi

Fri May 20 00:23:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 42%   43C    P0    28W /  90W |    914MiB /  2048MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.vstack([t, a])

tensor([[1., 1., 1.],
        [5., 5., 5.]], device='cuda:0')

In [ ]:
norm(t.cpu().numpy())

1.7320508

In [ ]:
t[1] += 1

In [ ]:
t

tensor([1., 2., 1.], device='cuda:0')

In [ ]:
torch.zeros(3)

tensor([0., 0., 0.])

In [ ]:
np.array([1, 2, 3])[1].item()

2

In [ ]:
print(t)
t[1] += t[2] - 5 * 3.5

tensor([1., 2., 1.], device='cuda:0')


In [ ]:
t

tensor([  1.0000, -14.5000,   1.0000], device='cuda:0')

In [ ]:
t += np.random.uniform(-1 / 20, 1 / 20)

In [ ]:
t

tensor([  1.0029, -14.4971,   1.0029], device='cuda:0')

In [ ]:
t[0] -= 1234

In [ ]:
t[1] = 0.123123123123

In [ ]:
t.cpu().numpy()

array([-1.23299707e+03,  1.23123124e-01,  1.00287974e+00], dtype=float32)

In [ ]:
!nvidia-smi

Fri May 20 00:23:56 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.68.02    Driver Version: 510.68.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 42%   43C    P0    28W /  90W |    913MiB /  2048MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from math import pow, sqrt
import numpy as np

In [ ]:
kT = 26.5
N = 150

Пиковое значение распределния Максвелла:

In [ ]:
sqrt(1. / (2 * np.pi * kT)) * (8 * np.pi * kT / np.e)

18.98796316581417

In [ ]:
import pandas as pd

In [ ]:
dic = {'a': [1], 'b': [2], 'c': [3]}

df = pd.DataFrame(
    dic
)

df = pd.concat([df, pd.DataFrame({'a': [1], 'b': [2], 'c': [3]})])

df

a  b  c
0  1  2  3
0  1  2  3

In [ ]:
1 in list(df.a)

[1, 1]

In [22]:
a = np.random.rand(4)

b = np.random.rand(4)

a, b

(array([0.1201665 , 0.38379309, 0.56685812, 0.84110428]),
 array([0.69345182, 0.57582825, 0.19101114, 0.70189508]))

In [23]:
((a - b) ** 2).mean()

array([0.32865606, 0.0368775 , 0.14126095, 0.0193792 ])